CATEGORIES={
    'Books': [],
    'Car': [],
    'Clothes': [],
    'Electricity': ['Enel'],
    'Entertainment': ['Cinema', 'Theatre'],
    'Food&Drink': ['Dinner', 'Meals'],
    'Fuel': ['Gas', 'Car Fuel'],
    'Gifts': ['Presents'],
    'Groceries': [],
    'Health': [],
    'Home': [],
    'Personal': [],
    'Rent': [],
    'Salary': [],
    'Sport': [],
    'Tech': [],
    'Telephone': [],
    'Travel': [],
}
