CATEGORIES = {
    'Books': [],
    'Car': [],
    'Clothes': [],
    'Electricity': ['Enel'],
    'Entertainment': ['Cinema', 'Theatre', 'Svago'],
    'Food&Drink': ['Dinner', 'Meals'],
    'Fuel': ['Gas', 'Car Fuel'],
    'Gifts': ['Presents', 'Regali'],
    'Groceries': [],
    'Health': ['Salute'],
    'Home': ['Bollette'],
    'Personal': [],
    'Rent': [],
    'Salary': ['Stipendi'],
    'Sport': [],
    'Tech': [],
    'Telephone': ['Telephone'],
    'Travel': [],
}
